### ISSUE TITLE
Create method to toggle a permission

### ISSUE THREAD

**Issue by lukeacraven** [RamanujansGhost/s87powers#11]
For example, a player with s87powers.lumberjack could do /powers toggle lumberjack to give themselves the s87powers.lumberjack.toggled permission.  The latter permission would be checked when a player's lumberjack permission is checked.  Of course, /powers toggle lumberjack would set s87powers.lumberjack.toggled to false.

**Comment by BlipRanger** [comment]
This now exists in S87Powers class under the command listener.
