### ISSUE TITLE
Modify wolfpack spawning code to ensure wolves spawn at a similar Y level as the player character

### ISSUE THREAD

**Issue by lukeacraven** [RamanujansGhost/s87powers#17]
This will involve looping until a valid spot is found, and not accepting any spot lower than the player.  Perhaps it should start searching at the y level of the player's feet.

**Comment by BlipRanger** [comment]
@RamanujansGhost - Isn't this fixed with the sky-drop dealio?

**Comment by lukeacraven** [comment]
It is, this is from when I wanted it to summon them on the sameish y level as the player.  I think it makes more sense lore-wise for it to be a surface-only thing though, so I will close this issue.
