### ISSUE TITLE
Can we make a player sleep?

### ISSUE THREAD

**Issue by BlipRanger** [RamanujansGhost/s87powers#25]
@RamanujansGhost - At any given point, can we cause a player to go through the sleep mode as if they laid down in a bed?

**Comment by lukeacraven** [comment]
Yes and no -- I researched it, and it looks like it can be done if you manually send the packet, but no API call exists.  See this [bukkit](https://bukkit.org/threads/mimicking-player-sleep-animation.89583/) thread and this [source](https://gist.github.com/aadnk/3954903)  on github.  In particular, this seems to be their packet constructor: `PacketContainer sleepPacket = packetConstructor.createPacket(
                    player, 0, loc.getBlockX(), loc.getBlockY() + 2, loc.getBlockZ());`

It is then sent via a protocolmanager, the code for sending the packet is on that github link too.  The code seems to be from an older version of bukkit, but I suspect the solution works with some syntax changes.

**Comment by BlipRanger** [comment]
Tabling this idea until we decide if we want packet manipulation. Not even sure why I wanted sleep...
